"all":
  "children":
    "kernel_update_targets":
      "hosts":
        "i-03b22be8bc93aefb1":
          "ansible_aws_ssm_region": "us-east-1"
          "ansible_connection": "aws_ssm"
          "ansible_host": "i-03b22be8bc93aefb1"
          "instance_name": "kiu-2"
          "private_ip": "10.0.1.154"
          "public_ip": "107.23.66.78"
        "i-07084aa91e285a333":
          "ansible_aws_ssm_region": "us-east-1"
          "ansible_connection": "aws_ssm"
          "ansible_host": "i-07084aa91e285a333"
          "instance_name": "kiu-1"
          "private_ip": "10.0.1.74"
          "public_ip": "44.200.202.190"
